
// This file is auto-generated by `npm run gen:categories`. Do not edit it manually.

export type CategoryCount = {
  name: string;
  count: number;
  slug: string;
};

export const categories: CategoryCount[] = [
  {
    "name": "berita",
    "count": 3,
    "slug": "berita"
  }
];
